name: Sync with Upstream

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/wshobson/agents.git || true
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge upstream/main --no-edit || echo "Merge conflict or no changes"

      - name: Push changes
        run: |
          git push origin main || echo "Nothing to push"